# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
name: termdepositsolutionchecker-webapp
dependencies:
python=3.8
matplotlib
numpy
pandas
scikit-learn
streamlit
